topics:
  users: users
  users-state: users-state
  
consumers:
  user-state: user-state-builder
  user-mail: user-mailer

spring:
  kafka:
    producer:
      transaction-id-prefix: user-application
      value-serializer: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerializer